name: Build package
on:
  push:
    branches: [ "main" ]

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build package
        run: ./setup-arch.sh

      - name: Uploading as artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          retention-days: 1
          path: |
            ~/built-packages/*
